- id: 阳光-通识
  name: 阳光服务队、极速之星《阳光选课攻略之通识类教育》
  url: https://mp.weixin.qq.com/s/N9mx8m8GWaYibCxuoqO50Q
  date: 2018-01-06
- id: 阳光-体育
  name: 阳光服务队、极速之星《阳光选课攻略之体育课》
  url: https://mp.weixin.qq.com/s/FPBkhTi3sQJ9Vnposm3JPQ
  date: 2018-01-06
- id: 阳光-实验
  name: 阳光服务队、极速之星《阳光选课攻略之实验选修类》
  url: https://mp.weixin.qq.com/s/186gfLWgBzGU7KLDzqp15g
  date: 2018-01-06
- id: 阳光-英语
  name: 阳光服务队、极速之星《阳光选课攻略之专项英语类》
  url: https://mp.weixin.qq.com/s/LKKggFotjZCfORdCh0bJWw
  date: 2018-01-06
